
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Migrations/CLI must use the direct (session-mode, 5432) connection.
    // The pgBouncer transaction pooler (DATABASE_URL, 6543) can't take the
    // session-level advisory locks that `migrate deploy` needs and will hang.
    // The runtime PrismaClient still uses DATABASE_URL from schema.prisma.
    url: env("DIRECT_URL"),
  },
});
